name: sugar_sense
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path: ^1.8.3
  english_words: ^4.0.0
  provider: ^6.1.2
  image_picker: ^1.0.7
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  http: ^1.2.0
  logging: ^1.2.0
  sqflite_common_ffi: ^2.3.2+1
  shared_preferences: ^2.2.2
  url_launcher: ^6.0.12
  intl: ^0.19.0
  path_provider: ^2.0.8
  fl_chart: ^0.67.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/splash.png
    - assets/letsgo.png
    - assets/signin.png
    - assets/crown.png
    - assets/diamond.png
    - assets/signup.png
    - assets/badge.png
    - assets/badge2.png
    - assets/security-safe.png
    - assets/AddDish.png
    - assets/no-pictures.png
    - assets/afandi.jpg
    - assets/Albeni.jpeg
    - assets/apples.jpg
    - assets/apricots.jpg
    - assets/Ashta.jpeg
    - assets/balah.jpeg
    - assets/Balilah.jpg
    - assets/bananas.jpg
    - assets/Batata Souffleh.jpg
    - assets/Beans.jpg
    - assets/Beer.png
    - assets/berries.jpg
    - assets/Borma.jpg
    - assets/bownies.jpg
    - assets/bread loaf.jpg
    - assets/Burgul.jpg
    - assets/cactus.jpg
    - assets/candies.jpg
    - assets/carrots.jpg
    - assets/cheesecake.jpg
    - assets/cherries.jpg
    - assets/chestnut.jpg
    - assets/chickpeas.jpg
    - assets/chips.jpg
    - assets/Choco prince.jpeg
    - assets/chocolate cereal.jpg
    - assets/concentrated juice (jellab).jpeg
    - assets/cooked oatmeal.jpg
    - assets/cooked veggies.jpg
    - assets/markouk.jpeg
    - assets/cookies.jpg
    - assets/Cordon Bleu.jpg
    - assets/corn.jpg
    - assets/cornflakes plain.jpg
    - assets/Crackers.jpg
    - assets/crepe.jpg
    - assets/croissant medium.jpg
    - assets/croissant small.jpg
    - assets/Custard.jpg
    - assets/Debess Roman.jpeg
    - assets/Debess.jpg
    - assets/diabetic jam.jpg
    - assets/digestive x2.jpg
    - assets/donuts.jpg
    - assets/dried apples.jpg
    - assets/dried apricots.jpg
    - assets/dried fig.jpg
    - assets/dried oatmeal.jpg
    - assets/eclairs.jpg
    - assets/Escalope.jpeg
    - assets/falafel.jpg
    - assets/Fasoliya.jpg
    - assets/Fatayir Bl Jobna.jpeg
    - assets/Fatayir Bl Sabanikh.jpg
    - assets/fig.jpg
    - assets/flour.jpg
    - assets/Foul Mdammas.jpg
    - assets/french fries.jpg
    - assets/fruit milkshake.png
    - assets/fruit salad.jpg
    - assets/Ghandour 555.jpg
    - assets/Ghraybeh.jpg
    - assets/grapefruit.jpg
    - assets/grapes.jpg
    - assets/Grilled Potato.jpg
    - assets/guava.jpg
    - assets/Halawet El-Jeben.jpg
    - assets/hamburger bread.jpeg
    - assets/honey.jpg
    - assets/hummus.jpg
    - assets/ice cream.jpg
    - assets/ikidinyah.jpg
    - assets/innab.jpeg
    - assets/jam.jpg
    - assets/Jazarieh.jpg
    - assets/kaak long.JPG
    - assets/kaak small.jpeg
    - assets/kator diabtic.jpeg
    - assets/kator.jpeg
    - assets/Kebbe Bl Saniyeh.jpg
    - assets/ketchup.jpg
    - assets/kharma.jpeg
    - assets/khoboz arabi large.jpg
    - assets/Khooboz arabi small.jpeg
    - assets/Kinders (x2).png
    - assets/kishk.jpg
    - assets/kitkat.jpeg
    - assets/kiwi.jpg
    - assets/Kol W Chkor.jpg
    - assets/Koussa Mahshi.jpg
    - assets/Kunefe.jpg
    - assets/Laban.jpg
    - assets/lasagna.jpg
    - assets/lentil soup.jpg
    - assets/lentils.jpg
    - assets/Leo.jpeg
    - assets/Lion.jpeg
    - assets/Maamool.jpg
    - assets/Mafroukeh Bl-Ashta.jpg
    - assets/makaroni with beef.jpg
    - assets/Makaroni With Cheese.jpg
    - assets/Makaroni.jpg
    - assets/Malfoof Mahshi.jpg
    - assets/Maltesers.jpg
    - assets/mango.jpg
    - assets/Mankousha.jpg
    - assets/markouk - saj.jpg
    - assets/Mars.jpeg
    - assets/melon.jpg
    - assets/milk.jpg
    - assets/milkshakes.jpeg
    - assets/moajanet.jpeg
    - assets/Moghrabieh.jpg
    - assets/moghli.jpeg
    - assets/Mohalabiyeh.jpg
    - assets/muffins big.jpg
    - assets/muffins small.jpg
    - assets/halawat riz.jpeg
    - assets/Nammoura.jpg
    - assets/Natural juice.jpg
    - assets/Nouba.jpg
    - assets/Number 1.jpg
    - assets/nutella.jpg
    - assets/Onion Soup.jpg
    - assets/orange.jpg
    - assets/Oreo x2.jpeg
    - assets/Osmaliyeh.jpg
    - assets/pain au lait.jpeg
    - assets/pancake.jpg
    - assets/papaya.jpg
    - assets/Pasta Salad.jpeg
    - assets/peach.jpg
    - assets/peanut butter.jpg
    - assets/pears.jpg
    - assets/peas.jpg
    - assets/petit four.jpg
    - assets/pickup.jpg
    - assets/pineapple.jpg
    - assets/pizza.jpg
    - assets/plums.jpg
    - assets/pomegranate.jpg
    - assets/popcorn.jpg
    - assets/potato.jpg
    - assets/powdered milk.jpg
    - assets/pretzels.jpg
    - assets/quinoa cooked.jpg
    - assets/raisins.jpg
    - assets/rice cakes.jpg
    - assets/rice.jpg
    - assets/Riz-bi-Haleeb.jpg
    - assets/roasted nuts.jpg
    - assets/ruit cocktail.jpeg
    - assets/safarjal.jpeg
    - assets/Sambousak Bi Jobna.jpg
    - assets/Smeed.jpg
    - assets/Snicker.jpeg
    - assets/Soft Drinks.jpg
    - assets/strawberry.jpg
    - assets/sugar.jpg
    - assets/sushi.jpg
    - assets/Sweetenedjuice.jpg
    - assets/tabbouleh.jpg
    - assets/termos.jpg
    - assets/Time out.jpg
    - assets/toast medium.jpg
    - assets/toast small.jpg
    - assets/toast soft.jpg
    - assets/toutt.jpeg
    - assets/Twirl.jpeg
    - assets/twix top.png
    - assets/Twix x2.jpeg
    - assets/Unica.jpg
    - assets/veggie soup.jpg
    - assets/wafers.jpg
    - assets/Warak Enab.jpg
    - assets/watermelon.jpg
    - assets/Wheat.jpg
    - assets/yogurt with fruits.jpg
    - assets/Znoud El Set.jpg
    - assets/completed.png
    - assets/All.png
    - assets/Arabic desserts.png
    - assets/Breakfast.png
    - assets/Dairy products.png
    - assets/Dinner.png
    - assets/Fruits.png
    - assets/Drinks.png
    - assets/Grains, pasta & rice.png
    - assets/Lebanese dishes.png
    - assets/Lunch.png
    - assets/My Meals.png
    - assets/Pastries.png
    - assets/Sweet & snacks.png
    - assets/bread.png
    - assets/insulin.png
    - assets/blood.png
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
    - family: InterBlack
      fonts:
        - asset: fonts/Inter-Black.ttf
          #weight: 900
    - family: Italiana
      fonts:
        - asset: fonts/Italiana-Regular.ttf
    - family: Ruda
      fonts:
        - asset: fonts/Ruda-Regular.ttf
    - family: Ruda-SemiBold
      fonts:
        - asset: fonts/Ruda-SemiBold.ttf
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
    - family: Sarabun
      fonts:
        - asset: fonts/Sarabun-Regular.ttf
    - family: Inder
      fonts:
        - asset: fonts/Inder-Regular.ttf
    - family: InriaSerif
      fonts:
        - asset: fonts/InriaSerif-Regular.ttf
    - family: InriaSerifBold
      fonts:
        - asset: fonts/InriaSerif-Bold.ttf
        - weight: 800
        
        
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
